### ISSUE TITLE
New resource: Code Catalog

### ISSUE THREAD

**Issue by ainzzorl** [lostdesign/webgems#285]
**Name**
Code Catalog

**Description**
A Collection of instructive code examples from prominent open source projects.

**URL**
https://codecatalog.org

**Category**
General

**Comment by lostdesign** [comment]
Thanks for the PR and Issue - I have reviewed the site and came to the conclusion that it does not fit webgems, as it does not relate that much to webdev.

Once more webdev related content exists as well as it being easier to explore, it may be added.
